# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 04:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms', models.CharField(max_length=200)),
                ('Stakes', models.CharField(max_length=300)),
                ('Due_date', models.DateTimeField(default=datetime.datetime(2017, 3, 17, 4, 5, 34, 64194, tzinfo=utc))),
                ('Status', models.IntegerField()),
                ('Public', models.BooleanField()),
                ('Date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.IntegerField()),
                ('user2_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('action_user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Date_joined', models.DateTimeField()),
                ('Wins', models.IntegerField(default=0)),
                ('Losses', models.IntegerField(default=0)),
                ('WinPercent', models.IntegerField(default=0)),
                ('LossPercent', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('user1_id', 'user2_id')]),
        ),
        migrations.AddField(
            model_name='bet',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='Wager.User'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='Wager.User'),
        ),
    ]
