# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Wager', '0002_auto_20170610_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='Due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 7, 22, 609352, tzinfo=utc)),
        ),
    ]
