# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Wager', '0003_auto_20170729_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='Due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 8, 7, 238565, tzinfo=utc)),
        ),
    ]
