# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Wager', '0004_auto_20170729_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='Due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 18, 17, 29, 209441, tzinfo=utc)),
        ),
    ]
